modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="goblinsanddungeons" #mandatory
version="1.0.8" #mandatory
displayName="Goblins & Dungeons" #mandatory
credits="superlord9362 (code and voice acting), Weastian (art), Ralof (art), Crimes Against Art (art), Mr. Esuoh (noises and voice acting), and Ninni (voice acting)" #optional
authors="superlord9362" #optional
description='''Goblins & Dungeons is a mod about dungeons and mythical creatures, with the purpose of giving the player a more complete and adventurous story throughout the game. The mod is mainly inspired by D&D type of RPG’s and the whole concept of dungeons.'''

[[dependencies.goblinsanddungeons]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.goblinsanddungeons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
